const LISTING_PAGE = "LISTING_PAGE";
const ADDRESS_PAGE = "ADDRESS_PAGE";
const CART_PAGE = "CART_PAGE";
const PRICE_FORMAT = "Rs."
const SUCCESS_PAGE = "SUCCESS_PAGE"
const ERROR_PAGE = "ERROR_PAGE"
const BUTTON_TYPE = {
    PRIMARY: "PRIMARY"
}
const STATUS = {
    IDLE: "IDLE",
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    REJECTED: "REJECTED"
}

export {
    LISTING_PAGE,
    ADDRESS_PAGE,
    CART_PAGE,
    PRICE_FORMAT,
    SUCCESS_PAGE,
    ERROR_PAGE,
    STATUS,
    BUTTON_TYPE
}